Update openlab scripts.
1. Add usb serial related scripts.
2. fix some other bugs.

Signed-off-by: cailianchun <armstar@sina.com>

diff --git a/board_reboot b/board_reboot
--- a/board_reboot
+++ b/board_reboot
@@ -91,6 +91,9 @@ done
 if [ x"$BOARD_NO" = x"" ]; then
 	if [ x"$BOARD_INDEX" != x"" ]; then
 		user_boards=($(get_user_boards $USER))
+		if [ $BOARD_INDEX -lt 0 ] || [ $BOARD_INDEX -ge ${#user_boards[@]} ]; then
+			echo -e "\033[31mInvalid board index! Please use board_list to get your board info!\033[0m" >&2 ; exit 1
+		fi
 		BOARD_NO=${user_boards[$BOARD_INDEX]}
 	else
 		user_boards=($(get_user_boards $USER))
@@ -102,7 +105,7 @@ fi
 # Check board and operate the power
 #############################################################################
 if !(get_board_info $BOARD_NO >/dev/null); then
-	echo -e "\033[31mCan't find board info ......\033[0m" ; exit 0
+	echo -e "\033[31mCan't find board info! Please touch Lab admin to get more help!\033[0m" ; exit 0
 fi
 
 if !(board_deploy_chk $BOARD_NO); then
